apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicename.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "servicename.fullname" . }}
  {{- $files := .Files }}
data:
{{ (.Files.Glob "*.conf").AsConfig | indent 2 }}
