replicaCount: 1
image:
  repository: registry.dar.kz/griffon/user-data-remover
  tag: N/A
  pullPolicy: IfNotPresent

nameOverride: user-data-remover
fullnameOverride: user-data-remover

# internal config name for service
configPath: /config
containerPort: 8080
service:
  type: ClusterIP
  targetPort: 8080
  port: 80

imagePullSecrets: regcred

ingress:
  enabled: "true"
  annotations: 
    kubernetes.io/ingress.class: ingress
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - griffon.dar-dev.zone
  # tls: 
  #  - secretName: example-tls
  #    hosts:
  #      - example.local

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

enviroment: qa

env:
  PORT: 8080
  